#!/usr/bin/env bash
set -e
input="$1"
output="$2"

[ -e "$input" ] || { echo "Input file '$input' does not exist" >&2; exit 1; }

soxi "$input" | grep -i duration | perl -ne '/(\d+\s*samples)/i && print STDERR "Total duration: $1\n"'
command="import threepy.nonspeech.cortical_utils as Utils; cp = Utils.CubePlot('$input'); cp.write_movie('$output')"
echo $command
python -c "$command"
mv $output $output.tmp
ffmpeg -i $output.tmp -i $input -map 0:v -map 1:a $output
rm $output.tmp