#!/usr/bin/env bash

set -e
input="$1"
output="$2"

if [ ! -e "$input" ]; then
  echo "Input file '$input' does not exist" >&2
  exit 1
fi

soxi "$input" | grep -i duration | perl -ne '/(\d+\s*samples)/i && print STDERR "Total duration: $1\n"'

python <<-PROGRAM
from cortio.plot.cube_plot import CubePlot
cp = CubePlot('$input')
cp.write_movie('$output')
PROGRAM

mv $output $output.tmp
ffmpeg -i $output.tmp -i $input -c:v copy -map 0:v -map 1:a $output
rm $output.tmp
